apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: web
          image: nginx:1.25.3      # ✅ good: pinned tag
          securityContext:
            privileged: false      # ✅ good: not privileged
          ports:
            - containerPort: 80
