apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: web
          image: nginx:latest     # ❌ bad: floating 'latest' tag
          securityContext:
            privileged: true      # ❌ bad: privileged container
          ports:
            - containerPort: 80
